[2022-06-01 20:03:41,334] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: user_processing.processing_users __airflow_temporary_run_2022-06-01T10:53:33.458279+00:00__ [queued]>
[2022-06-01 20:03:41,338] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: user_processing.processing_users __airflow_temporary_run_2022-06-01T10:53:33.458279+00:00__ [queued]>
[2022-06-01 20:03:41,338] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 20:03:41,338] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-06-01 20:03:41,338] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 20:03:41,348] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): processing_users> on 2022-01-01 00:00:00+00:00
[2022-06-01 20:03:41,367] {standard_task_runner.py:52} INFO - Started process 11762 to run task
[2022-06-01 20:03:41,372] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'processing_users', '__airflow_temporary_run_2022-06-01T10:53:33.458279+00:00__', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpju51pb4t', '--error-file', '/tmp/tmp9xwc4hua']
[2022-06-01 20:03:41,374] {standard_task_runner.py:80} INFO - Job 20: Subtask processing_users
[2022-06-01 20:03:41,408] {task_command.py:370} INFO - Running <TaskInstance: user_processing.processing_users __airflow_temporary_run_2022-06-01T10:53:33.458279+00:00__ [running]> on host TIGER0990.tigeranalytics.local
[2022-06-01 20:03:41,442] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_users
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=__airflow_temporary_run_2022-06-01T10:53:33.458279+00:00__
[2022-06-01 20:03:41,454] {python.py:173} INFO - Done. Returned value was: None
[2022-06-01 20:03:41,458] {taskinstance.py:1396} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_users, execution_date=20220101T000000, start_date=20220601T143341, end_date=20220601T143341
[2022-06-01 20:03:41,506] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-01 20:03:41,531] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
